# Hadolint configuration
# See: https://github.com/hadolint/hadolint#configure

ignored:
  # DL3008: Pin versions in apt get install
  # We use Ubuntu base image with cache mounts - pinning apt versions
  # is not practical for a devcontainer
  - DL3008

  # DL3013: Pin versions in pip
  # Not using pip in this Dockerfile

  # DL3059: Multiple consecutive RUN instructions
  # We intentionally separate layers for caching
  - DL3059
